name: Theme Update
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ls -a via OPEN SSH Private Key
        uses: mrpatg/ssh-action@master
        with:
          command: |
            cd /var/www/build.patrickgodbey.com/htdocs/wp-content/themes/patrickgodbeycom_theme
            git pull
          host: ${{ secrets.HOST }}
          user: github
          pass: ${{ secrets.PASS }}
          args: "-tt -v"
